services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=mini_ledger'
      - 'POSTGRES_PASSWORD=ledger'
      - 'POSTGRES_USER=ledger'
    ports:
      - '5433:5432'
  redis:
    image: 'redis:7'
    ports:
      - '6379:6379'
